package src.events;

public enum EventType {


    ELEVATOR_TRAVERSED_FLOOR,
    ELEVATOR_ARRIVED,
    ELEVATOR_DEPARTED,
    ELEVATOR_LOADING,
    ELEVATOR_UNLOADING,
    ELEVATOR_DOOR_OPENING,
    ELEVATOR_DOOR_OPEN,
    ELEVATOR_DOOR_CLOSING,
    ELEVATOR_DOOR_CLOSED,
    ELEVATOR_RECEIVED_REQUEST,
    SCHEDULER_RECEIVED_REQUEST,
    SCHEDULER_MOVE_TO_IDLE
}